import {
  Activity,
  Contact,
  EmotionalConfig,
  EmotionalState,
  SharedMemory,
  JournalPrompt,
  DiscoverItem,
  Plan,
} from './types';

export const PRIMARY_FRIEND: Contact = {
  id: 'riya',
  name: 'Riya Sharma',
  initials: 'RS',
  phone: '+1 (555) 018-9241',
  location: 'Brooklyn, NY (15 min away)',
  avatarBg: '#EDE9FE',
};

export const CONTACT_SUGGESTIONS: Contact[] = [
  PRIMARY_FRIEND,
  {
    id: 'maya',
    name: 'Maya Lin',
    initials: 'ML',
    phone: '+1 (555) 019-2831',
    location: 'Lower East Side',
    avatarBg: '#FEF3C7',
  },
  {
    id: 'alex',
    name: 'Alex Rivera',
    initials: 'AR',
    phone: '+1 (555) 014-4920',
    location: 'Greenpoint',
    avatarBg: '#ECFDF5',
  },
  {
    id: 'jordan',
    name: 'Jordan Taylor',
    initials: 'JT',
    phone: '+1 (555) 017-8839',
    location: 'Crown Heights',
    avatarBg: '#FDF2F8',
  },
];

export const EMOTIONAL_CONFIGS: Record<EmotionalState, EmotionalConfig> = {
  fun: {
    id: 'fun',
    label: 'Fun',
    dotColor: '#F59E0B',
    bgColor: '#FEF3C7',
    textColor: '#92400E',
    borderColor: '#FDE68A',
    description: 'Playful energy, laughter, and high spirits',
  },
  calming: {
    id: 'calming',
    label: 'Calming',
    dotColor: '#818CF8',
    bgColor: '#EEF2FF',
    textColor: '#3730A3',
    borderColor: '#C7D2FE',
    description: 'Slow pace, deep breath, restorative stillness',
  },
  meaningful: {
    id: 'meaningful',
    label: 'Meaningful',
    dotColor: '#EC4899',
    bgColor: '#FDF2F8',
    textColor: '#9D174D',
    borderColor: '#FBCFE8',
    description: 'Heartfelt vulnerability and thoughtful connection',
  },
  unexpected: {
    id: 'unexpected',
    label: 'Unexpected',
    dotColor: '#F97316',
    bgColor: '#FFF7ED',
    textColor: '#9A3412',
    borderColor: '#FED7AA',
    description: 'A surprising twist, spontaneous discovery or revelation',
  },
  'just-nice': {
    id: 'just-nice',
    label: 'Just nice',
    dotColor: '#10B981',
    bgColor: '#ECFDF5',
    textColor: '#065F46',
    borderColor: '#A7F3D0',
    description: 'Simple comfort, natural flow, easy company',
  },
};

export const CURATED_ACTIVITIES: Activity[] = [
  {
    id: 'walk',
    title: 'Take a walk',
    duration: '15–30 min',
    description: 'A simple walk with no agenda. Talk, wander, or just enjoy the fresh air together.',
    iconName: 'walk',
    locationType: 'in-person',
    tags: ['Simple', 'Outdoors', 'Low effort'],
  },
  {
    id: 'sunset',
    title: 'Watch the sunset',
    duration: '15–30 min',
    description: 'Catch the day fading into evening from a bench, window, or local vantage point.',
    iconName: 'sunset',
    locationType: 'either',
    tags: ['Relaxing', 'Peaceful'],
  },
  {
    id: 'cook',
    title: 'Cook the same meal',
    duration: '30–60 min',
    description: 'Pick a simple recipe together and cook side-by-side or over video.',
    iconName: 'utensils',
    locationType: 'either',
    tags: ['Hands-on', 'Comforting'],
  },
  {
    id: 'game',
    title: 'Play a quick game',
    duration: '15–30 min',
    description: 'A round of cards, word puzzle, or phone game just for the fun of it.',
    iconName: 'gamepad',
    locationType: 'either',
    tags: ['Playful', 'Quick'],
  },
  {
    id: 'playlist',
    title: 'Make a playlist together',
    duration: '20–30 min',
    description: 'Trade 5 songs each that remind you of this season or memories you share.',
    iconName: 'music',
    locationType: 'remote',
    tags: ['Creative', 'Anytime'],
  },
  {
    id: 'coffee',
    title: 'Have coffee together',
    duration: '20–30 min',
    description: 'A quiet cup at a corner café or sitting on a porch before the day gets noisy.',
    iconName: 'coffee',
    locationType: 'in-person',
    tags: ['Routine', 'Easy'],
  },
  {
    id: 'read',
    title: 'Read something together',
    duration: '20–40 min',
    description: 'Read the same short article, poem, or book chapter and discuss two lines.',
    iconName: 'book',
    locationType: 'either',
    tags: ['Reflective', 'Quiet'],
  },
  {
    id: 'new-thing',
    title: 'Try something neither of you has done',
    duration: '30–60 min',
    description: 'Step into a new bakery, try origami, or take an unfamiliar route home.',
    iconName: 'compass',
    locationType: 'in-person',
    tags: ['Adventure', 'Novelty'],
  },
  {
    id: 'photo-challenge',
    title: 'Send each other a photo challenge',
    duration: '10–15 min',
    description: 'Give each other three specific things to spot and photograph right now.',
    iconName: 'camera',
    locationType: 'remote',
    tags: ['Spontaneous', 'Visual'],
  },
  // Additional library items for "View all activities"
  {
    id: 'sketch',
    title: '5-minute blind portrait sketch',
    duration: '10–15 min',
    description: 'Sketch each other without looking at the paper and laugh at the outcome.',
    iconName: 'palette',
    locationType: 'in-person',
    tags: ['Creative', 'Laughter'],
  },
  {
    id: 'bike-ride',
    title: 'Slow afternoon bike spin',
    duration: '30–45 min',
    description: 'Pedal gently through quiet side streets with zero rush.',
    iconName: 'bike',
    locationType: 'in-person',
    tags: ['Outdoors', 'Movement'],
  },
  {
    id: 'nostalgia',
    title: 'Revisit an old memory',
    duration: '15–20 min',
    description: 'Pull up a photo from 3 years ago and tell the story of what really happened.',
    iconName: 'sparkles',
    locationType: 'either',
    tags: ['Sentimental', 'Story'],
  },
];

export const INITIAL_PLAN: Plan = {
  id: 'plan-1',
  activityId: 'walk',
  activityTitle: 'Take a walk',
  duration: '15–30 min',
  date: 'Saturday',
  time: '6:00 PM',
  displayDateTime: 'Saturday · 6:00 PM',
  initiator: 'Komal',
  recipient: 'Riya',
  note: 'Want to try the new park by the water?',
  recurrence: 'weekly',
  recurrenceDuration: '1 month',
  status: 'accepted',
};

export const DEFAULT_PLAN = INITIAL_PLAN;

export const INITIAL_MEMORIES: SharedMemory[] = [
  {
    id: 'mem-1',
    activityTitle: 'Watch the sunset',
    dateStr: 'Sept 19 · 6:30 PM',
    month: 'SEPTEMBER',
    year: '2026',
    userEmotion: 'calming',
    friendEmotion: 'fun',
    userEmotionLabel: 'Calming',
    friendEmotionLabel: 'Fun',
    photoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    note: 'The sky turned lavender and amber over the reservoir. We talked about autumn plans.',
  },
  {
    id: 'mem-2',
    activityTitle: 'Take a walk',
    dateStr: 'Sept 12 · 5:45 PM',
    month: 'SEPTEMBER',
    year: '2026',
    userEmotion: 'just-nice',
    friendEmotion: 'calming',
    userEmotionLabel: 'Just nice',
    friendEmotionLabel: 'Calming',
    photoUrl: 'https://images.unsplash.com/photo-1519337265831-281ec6cc8514?auto=format&fit=crop&w=600&q=80',
    note: 'Explored the quiet tree-lined blocks after the afternoon rain.',
  },
  {
    id: 'mem-3',
    activityTitle: 'Have dinner together',
    dateStr: 'Sept 4 · 7:15 PM',
    month: 'SEPTEMBER',
    year: '2026',
    userEmotion: 'meaningful',
    friendEmotion: 'meaningful',
    userEmotionLabel: 'Meaningful',
    friendEmotionLabel: 'Meaningful',
    photoUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
    note: 'Long conversation over warm ramen about how fast this year is going.',
  },
  {
    id: 'mem-4',
    activityTitle: 'Cook the same meal',
    dateStr: 'Aug 24 · 6:00 PM',
    month: 'AUGUST',
    year: '2026',
    userEmotion: 'fun',
    friendEmotion: 'unexpected',
    userEmotionLabel: 'Fun',
    friendEmotionLabel: 'Unexpected',
    photoUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=600&q=80',
    note: 'Both attempted lemon ricotta pasta. Riya accidentally added chili flakes and it was delicious.',
  },
  {
    id: 'mem-5',
    activityTitle: 'Art workshop',
    dateStr: 'Aug 10 · 2:00 PM',
    month: 'AUGUST',
    year: '2026',
    userEmotion: 'meaningful',
    friendEmotion: 'fun',
    userEmotionLabel: 'Meaningful',
    friendEmotionLabel: 'Fun',
    photoUrl: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=600&q=80',
    note: 'Clay mug making at the community studio. Neither of ours held water but we loved it.',
    isMilestone: true,
    milestoneTitle: 'First community experience together',
  },
  {
    id: 'mem-6',
    activityTitle: 'Movie night',
    dateStr: 'July 28 · 8:30 PM',
    month: 'JULY',
    year: '2026',
    userEmotion: 'just-nice',
    friendEmotion: 'calming',
    userEmotionLabel: 'Just nice',
    friendEmotionLabel: 'Calming',
    note: 'Rewatched Before Sunrise with homemade popcorn.',
  },
  {
    id: 'mem-7',
    activityTitle: 'Evening walk',
    dateStr: 'July 14 · 7:00 PM',
    month: 'JULY',
    year: '2026',
    userEmotion: 'calming',
    friendEmotion: 'calming',
    userEmotionLabel: 'Calming',
    friendEmotionLabel: 'Calming',
    note: 'Cool breeze off the pier after a scorching hot day.',
  },
];

export const JOURNAL_PROMPTS: JournalPrompt[] = [
  {
    id: 'jp-1',
    prompt: 'What is something small that made both of you laugh uncontrollably recently?',
    response: 'When Riya dropped her ice cream cone and a golden retriever caught it mid-air in one smooth gulp.',
    answeredBy: 'Komal & Riya',
    date: 'Aug 18, 2026',
    saved: true,
  },
  {
    id: 'jp-2',
    prompt: 'What habit or routine in your friend’s everyday life do you admire?',
    response: 'Riya always makes time for a 10-minute morning balcony tea, no matter how packed her work schedule is.',
    answeredBy: 'Komal',
    date: 'July 2, 2026',
    saved: true,
  },
  {
    id: 'jp-3',
    prompt: 'What is one thing you have learned through this friendship this year?',
    response: '',
    saved: false,
  },
  {
    id: 'jp-4',
    prompt: 'Describe a moment when you felt supported without either of you having to say anything.',
    response: '',
    saved: false,
  },
];

export const DISCOVER_ITEMS: DiscoverItem[] = [
  // For you two
  {
    id: 'disc-1',
    section: 'for-you',
    title: 'Golden Hour Audio Walk',
    subtitle: 'Synchronized walk with quiet prompts',
    dateTime: 'Any day at sunset',
    description: 'Put your earbuds in, head outside simultaneously, and describe the evening light.',
    category: 'Curated for You',
    duration: '20 min',
    badge: 'Popular for pairs',
  },
  {
    id: 'disc-2',
    section: 'for-you',
    title: 'Swap Childhood Neighborhood Stories',
    subtitle: 'Low-key evening coffee conversation',
    dateTime: 'Flexible',
    description: 'Show each other your childhood elementary schools on street view.',
    category: 'Curated for You',
    duration: '25 min',
  },
  // Experiences
  {
    id: 'disc-3',
    section: 'experiences',
    title: 'Make Something Together',
    subtitle: 'Ceramic Hand-Building Workshop',
    dateTime: 'Saturday · 5:00 PM',
    location: 'Cobble Hill Studio',
    description: 'A cozy 2-hour session shaping clay pinch pots with tea and lo-fi music.',
    category: 'Creative Workshop',
    duration: '2 hours',
    badge: 'Join with your friend',
  },
  {
    id: 'disc-4',
    section: 'experiences',
    title: 'Farmers Market Sourdough Tasting',
    subtitle: 'Tasting bread and local preserves',
    dateTime: 'Sunday · 10:30 AM',
    location: 'Grand Army Plaza',
    description: 'Stroll the market stalls, sample olive oils, and grab warm focaccia.',
    category: 'Food Experience',
    duration: '45 min',
    badge: 'Low friction',
  },
  // Community (wellbeing partners)
  {
    id: 'disc-5',
    section: 'community',
    title: 'Mindful Morning Walk in the Park',
    subtitle: 'Facilitated by Brooklyn Wellbeing Circle',
    dateTime: 'Saturday · 9:30 AM',
    location: 'Prospect Park Meadow',
    description: 'A gentle, phone-free stroll focusing on sensory grounding and friendly conversation.',
    category: 'Wellbeing Partner',
    duration: '45 min',
    badge: 'Partner Hosted',
  },
  {
    id: 'disc-6',
    section: 'community',
    title: 'Silent Book Club & Coffee',
    subtitle: 'Hosted by Books & Brevity',
    dateTime: 'Thursday · 6:30 PM',
    location: 'Corner Coffee Co.',
    description: 'Bring whatever book you are reading, read in companionable silence for 30 min, then catch up.',
    category: 'Community Gathering',
    duration: '1 hour',
    badge: 'Free & Welcoming',
  },
  // Near you
  {
    id: 'disc-7',
    section: 'near-you',
    title: 'Sunset over Pier 6 Waterfront',
    subtitle: '0.8 miles away · Quiet vantage point',
    dateTime: 'Best at 6:45 PM',
    location: 'Brooklyn Bridge Park',
    description: 'Secluded wooden benches overlooking the harbor lights as the ferry passes.',
    category: 'Local Gem',
    duration: '20–40 min',
  },
  {
    id: 'disc-8',
    section: 'near-you',
    title: 'Botanical Garden Greenhouse Walk',
    subtitle: '1.2 miles away · Free Tuesdays',
    dateTime: 'Tues–Sun · 10 AM–5 PM',
    location: 'Washington Ave Entrance',
    description: 'Lush tropical warmth and quiet pathways regardless of the weather outside.',
    category: 'Local Gem',
    duration: '45 min',
  },
];
